DEV_SAMPLES = 1000
TEST_SAMPLES = 5000

TXA_SAMPLE_SIZE = 250
TXB_SAMPLE_SIZE = 1000

SAMPLE_SIZE={
    'TXA': TXA_SAMPLE_SIZE,
    'TXB': TXB_SAMPLE_SIZE,
    'T1A': TXA_SAMPLE_SIZE,
    'T1B': TXB_SAMPLE_SIZE,
    'T2A': TXA_SAMPLE_SIZE,
    'T2B': TXB_SAMPLE_SIZE
}

ERROR_TOL = 1E-3
